# Generated by Django 6.0 on 2025-12-09 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='project_images/')),
                ('link', models.URLField(blank=True, null=True)),
                ('tags', models.CharField(help_text='Comma-separated tags', max_length=200)),
                ('date_completed', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
